locationsData={
    "loc-tech:club":1,
    "loc-tech:wooden_tools":2,
    "loc-tech:sundial":3,
    "loc-tech:housing":4,
    "loc-tech:agriculture":5,
    "loc-tech:mining":6,
    "loc-tech:stone_axe":7,
    "loc-tech:currency":8,
    "loc-tech:irrigation":9,
    "loc-tech:science":10,
    "loc-tech:metal_working":11,
    "loc-tech:storage":12,
    "loc-tech:garrison":13,
    "loc-tech:banking":14,
    "loc-tech:farm_house":15,
    "loc-tech:copper_axes":16,
    "loc-tech:copper_sledgehammer":17,
    "loc-tech:foundry":18,
    "loc-tech:copper_pickaxe":19,
    "loc-tech:copper_hoe":20,
    "loc-tech:government":21,
    "loc-tech:iron_mining":22,
    "loc-tech:silo":23,
    "loc-tech:bows":24,
    "loc-tech:armor":25,
    "loc-tech:cement":26,
    "loc-tech:investing":27,
    "loc-tech:spy":28,
    "loc-tech:artisans":29,
    "loc-tech:market":30,
    "loc-tech:iron_axes":31,
    "loc-tech:iron_sledgehammer":32,
    "loc-tech:iron_pickaxe":33,
    "loc-tech:iron_saw":34,
    "loc-tech:iron_hoe":35,
    "loc-tech:smelting":36,
    "loc-tech:coal_mining":37,
    "loc-tech:mercs":38,
    "loc-tech:republic":39,
    "loc-tech:socialist":40,
    "loc-tech:library":41,
    "loc-tech:theatre":42,
    "loc-tech:theology":43,
    "loc-tech:urban_planning":44,
    "loc-tech:reinforced_shed":45,
    "loc-tech:containerization":46,
    "loc-tech:apprentices":47,
    "loc-tech:rebar":48,
    "loc-tech:plate_armor":49,
    "loc-tech:cottage":50,
    "loc-tech:vault":51,
    "loc-tech:trade":52,
    "loc-tech:black_powder":53,
    "loc-tech:steel":54,
    "loc-tech:mill":55,
    "loc-tech:playwright":56,
    "loc-tech:thesis":57,
    "loc-tech:theocracy":58,
    # "loc-tech:anthropology":59,
    "loc-tech:tax_rates":60,
    "loc-tech:aphrodisiac":61,
    "loc-tech:bayer_process":62,
    "loc-tech:dynamite":63,
    "loc-tech:bonds":64,
    "loc-tech:carpentry":65,
    "loc-tech:flintlock_rifle":66,
    "loc-tech:reinforced_crates":67,
    "loc-tech:steel_rebar":68,
    "loc-tech:mad_science":69,
    "loc-tech:steel_sledgehammer":70,
    "loc-tech:steel_containers":71,
    "loc-tech:steel_axes":72,
    "loc-tech:steel_pickaxe":73,
    "loc-tech:steel_saw":74,
    "loc-tech:steel_beams":75,
    "loc-tech:steel_hoe":76,
    "loc-tech:blast_furnace":77,
    "loc-tech:research_grant":78,
    "loc-tech:hospital":79,
    # "loc-tech:mythology":80,
    "loc-tech:large_trades":81,
    "loc-tech:steel_vault":82,
    "loc-tech:espionage":83,
    "loc-tech:magic":84,
    "loc-tech:boot_camp":85,
    "loc-tech:master_crafter":86,
    "loc-tech:electricity":87,
    "loc-tech:barns":88,
    "loc-tech:diplomacy":89,
    "loc-tech:bessemer_process":90,
    "loc-tech:home_safe":91,
    "loc-tech:spy_training":92,
    # "loc-tech:archaeology":93,
    "loc-tech:apartment":94,
    "loc-tech:radio":95,
    "loc-tech:mine_conveyor":96,
    "loc-tech:cranes":97,
    "loc-tech:eebonds":98,
    "loc-tech:brickworks":99,
    "loc-tech:gantry_cranes":100,
    "loc-tech:jackhammer":101,
    "loc-tech:industrialization":102,
    "loc-tech:spy_gadgets":103,
    "loc-tech:merchandising":104,
    "loc-tech:corpocracy":105,
    "loc-tech:technocracy":106,
    "loc-tech:scientific_journal":107,
    "loc-tech:oil_well":108,
    "loc-tech:zoning_permits":109,
    "loc-tech:vocational_training":110,
    "loc-tech:signing_bonus":111,
    "loc-tech:portland_cement":112,
    "loc-tech:corruption":113,
    "loc-tech:freight":114,
    "loc-tech:titanium_axes":115,
    "loc-tech:titanium_sledgehammer":116,
    "loc-tech:warehouse":117,
    "loc-tech:titanium_hoe":118,
    "loc-tech:swiss_banking":119,
    "loc-tech:hunter_process":120,
    "loc-tech:oxygen_converter":121,
    "loc-tech:rotary_kiln":122,
    "loc-tech:oil_depot":123,
    "loc-tech:machine_gun":124,
    "loc-tech:adjunct_professor":125,
    "loc-tech:anfo":126,
    "loc-tech:wharf":127,
    "loc-tech:alloy_containers":128,
    "loc-tech:electronics":129,
    "loc-tech:titanium_crates":130,
    "loc-tech:oil_power":131,
    "loc-tech:tesla_coil":132,
    "loc-tech:code_breakers":133,
    "loc-tech:thermomechanics":134,
    "loc-tech:cameras":135,
    "loc-tech:machinery":136,
    "loc-tech:tv":137,
    "loc-tech:safety_deposit":138,
    "loc-tech:jackhammer_mk2":139,
    "loc-tech:assembly_line":140,
    "loc-tech:uranium":141,
    "loc-tech:screw_conveyor":142,
    "loc-tech:bunk_beds":143,
    "loc-tech:kroll_process":144,
    "loc-tech:electric_arc_furnace":145,
    "loc-tech:casino":146,
    "loc-tech:massive_trades":147,
    "loc-tech:titanium_drills":148,
    "loc-tech:internet":149,
    "loc-tech:wind_turbine":150,
    "loc-tech:uranium_storage":151,
    "loc-tech:fission":152,
    "loc-tech:dazzle":153,
    "loc-tech:bioscience":154,
    "loc-tech:alloy_drills":155,
    "loc-tech:arpa":156,
    "loc-tech:uranium_ash":157,
    "loc-tech:polymer":158,
    "loc-tech:gmfood":159,
    "loc-tech:urbanization":160,
    "loc-tech:stock_market":161,
    "loc-tech:genetics":162,
    "loc-tech:rocketry":163,
    "loc-tech:monument":164,
    "loc-tech:fracking":165,
    "loc-tech:kevlar":166,
    "loc-tech:fluidized_bed_reactor":167,
    "loc-tech:synthetic_fur":168,
    "loc-tech:mad":169,
    "loc-tech:robotics":170,
    "loc-tech:cnc_machine":171,

    "loc-build:basic_housing":172,
    "loc-build:cottage":173,
    "loc-build:apartment":174,
    "loc-build:farm":175,
    "loc-build:mill":176,
    "loc-build:windmill":177,
    "loc-build:silo":178,
    "loc-build:garrison":179,
    "loc-build:hospital":180,
    "loc-build:boot_camp":181,
    "loc-build:shed":182,
    "loc-build:storage_yard":183,
    "loc-build:warehouse":184,
    "loc-build:bank":185,
    "loc-build:lumber_yard":186,
    "loc-build:sawmill":187,
    "loc-build:rock_quarry":188,
    "loc-build:cement_plant":189,
    "loc-build:foundry":190,
    "loc-build:factory":191,
    "loc-build:smelter":192,
    "loc-build:metal_refinery":193,
    "loc-build:mine":194,
    "loc-build:coal_mine":195,
    "loc-build:oil_well":196,
    "loc-build:oil_depot":197,
    "loc-build:trade":198,
    "loc-build:wharf":199,
    "loc-build:amphitheatre":200,
    "loc-build:casino":201,
    "loc-build:temple":202,
    "loc-build:university":203,
    "loc-build:library":204,
    "loc-build:wardenclyffe":205,
    "loc-build:biolab":206,
    "loc-build:coal_power":207,
    "loc-build:oil_power":208,
    "loc-build:fission_power":209,
    # "loc-build:stock_exchange":210,
    # "loc-build:launch_facility":211,
    # "loc-build:monument":212,
    # "loc-build:railway":213,
    # "loc-build:lhc":214,
}

optionDependReqs={
    "relig":[True,{
        "loc-tech:theology":43,
        "loc-tech:theocracy":58,
        "loc-build:temple":202,
    }],
}

buildingReqs={
    "build-loc:basic_housing":"tech-item:housing",
    "build-loc:cottage":"tech-item:",
    "build-loc:apartment":"tech-item:apartment",
    "build-loc:farm":"tech-item:agriculture",
    "build-loc:mill":"tech-item:mill",
    "build-loc:windmill":"tech-item:",
    "build-loc:silo":"tech-item:silo",
    "build-loc:garrison":"tech-item:garrison",
    "build-loc:hospital":"tech-item:hospital",
    "build-loc:boot_camp":"tech-item:boot_camp",
    "build-loc:shed":"tech-item:storage",
    "build-loc:storage_yard":"tech-item:containerization",
    "build-loc:warehouse":"tech-item:steel_containers",
    "build-loc:bank":"tech-item:banking",
    "build-loc:lumber_yard":"tech-item:stone_axe",
    "build-loc:sawmill":"tech-item:iron_saw",
    "build-loc:rock_quarry":"tech-item:mining",
    "build-loc:cement_plant":"tech-item:cement",
    "build-loc:foundry":"tech-item:foundry",
    "build-loc:factory":"tech-item:industrialization",
    "build-loc:smelter":"tech-item:smelting",
    "build-loc:metal_refinery":"tech-item:bayer_process",
    "build-loc:mine":"tech-item:metal_working",
    "build-loc:coal_mine":"tech-item:coal_mining",
    "build-loc:oil_well":"tech-item:oil_well",
    "build-loc:oil_depot":"tech-item:oil_depot",
    "build-loc:trade":"tech-item:trade",
    "build-loc:wharf":"tech-item:wharf",
    "build-loc:amphitheatre":"tech-item:theatre",
    "build-loc:casino":"tech-item:casino",
    # "build-loc:temple":"tech-item:theology",
    "build-loc:university":"tech-item:science",
    "build-loc:library":"tech-item:library",
    "build-loc:wardenclyffe":"tech-item:mad_science",
    "build-loc:biolab":"tech-item:bioscience",
    "build-loc:coal_power":"tech-item:electricity",
    "build-loc:oil_power":"tech-item:oil_power",
    "build-loc:fission_power":"tech-item:fission",
    # "build-loc:stock_exchange":"tech-item:stock_market",
    # "build-loc:launch_facility":"tech-item:rocketry",
    # "build-loc:monument":"tech-item:monument",
    # "build-loc:railway":"tech-item:ARPA",
    # "build-loc:lhc":"tech-item:ARPA",
}
crisprItems={
    "item-crispr:creep_1":1500,
    "item-crispr:creep_2":1501,
    "item-crispr:creep_3":1502,
    "item-crispr:creep_4":1503,
    "item-crispr:creep_5":1504,
    "item-crispr:store_1":1505,
    "item-crispr:store_2":1506,
    "item-crispr:store_3":1507,
    "item-crispr:store_4":1508,
    "item-crispr:enhance_1":1509,
    "item-crispr:birth_1":1510,
    "item-crispr:crafty_1":1511,
    "item-crispr:crafty_2":1512,
    "item-crispr:crafty_3":1513,
    "item-crispr:queue_1":1514,
    "item-crispr:queue_2":1515,
    "item-crispr:queue_3":1516,
    "item-crispr:governor_1":1517,
    "item-crispr:governor_2":1518,
    "item-crispr:governor_3":1519,
    "item-crispr:trader_1":1520,
    "item-crispr:trader_2":1521,
    "item-crispr:ancients_3":1522,
    "item-crispr:ancients_4":1523,
    "item-crispr:ancients_5":1524,
    "item-crispr:ancients_6":1525,
    "item-crispr:transcendence_1":1526,
    "item-crispr:bleed_1":1527,
    "item-crispr:bleed_2":1528,
    "item-crispr:bleed_3":1529,
}
#hopefully these will work eventually
techItems={
    # "item-tech:electricity":1537,
    # "item-tech:industrialization":1538,
    # "item-tech:oil_well":1539,
    # "item-tech:mad_science":1540,
    # "item-tech:steel":1541,
    # "item-tech:arpa":1542,
    # "item-tech:uranium":1543,
    # "item-tech:rocketry":1544,
    # "item-tech:mad":1545,
}

techLocsPre={

    # "item-tech:electricity":["loc-tech:electricity"],
    # "item-tech:industrialization":["item-tech:industrialization"],
    # "item-tech:oil_well":["item-tech:oil_well"],
    # "item-tech:mad_science":["item-tech:mad_science"],
    # "loc-tech:steel":["item-tech:steel"],
    # "loc-tech:arpa":["item-tech:arpa"],
    # "loc-tech:uranium":["item-tech:uranium"],
    # "loc-tech:rocketry":["item-tech:rocketry"],
    # "loc-tech:mad":["item-tech:mad"],
}

fillerItems={
    # "item-filler:major_event":1525,
    # "item-filler:minor_event":1526,
    "item-filler:building":1600,
    "item-filler:resources":1601,
    "item-filler:plasmid_1":1602,# this is 1-10
    "item-filler:plasmid_2":1603,#10-50
    "item-filler:plasmid_3":1604,#50-100
    "item-filler:plasmid_4":1605,#100-200
    "item-filler:phage_1":1606,#1-10
    "item-filler:phage_2":1607,#10-25
    "item-filler:phage_3":1608,#25-50
    "item-filler:antiplasmid_1":1609,#10-20
    "item-filler:antiplasmid_2":1610,#1-10
    "item-filler:power_bonus":1611,
    "item-filler:prod_bonus":1612,
    "item-filler:pop_bonus":1613,
}
trapItems={
    "item-trap:resources":1700,
    "item-trap:power_malus":1701,
    "item-trap:prod_malus":1702,
    "item-trap:attack":1703,
}